dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/beta
sudo: required
dotnet: 3.1.202
language: csharp
solution: DataMatrix.sln
mono: none
script:
  - dotnet restore DataMatrix.sln
  - sudo snap alias dotnet-sdk.dotnet dotnet
